plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mubel.kantar'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mubel.kantar.v210'
        minSdk 23
        targetSdk 35
        versionCode 2100
        versionName '2.10.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['META-INF/LICENSE.md', 'META-INF/NOTICE.md', 'META-INF/LICENSE', 'META-INF/NOTICE']
        }
    }
}

dependencies {
    implementation 'com.sun.mail:android-mail:1.6.7'
    implementation 'com.sun.mail:android-activation:1.6.7'
}
