(()=>{'use strict';
const $=id=>document.getElementById(id);
const STORE='mubel2109_control_v1';
const COMMANDS=[['POWER','ON / OFF','⏻'],['ZERO','ZERO','0'],['TARE','TARE','T'],['HOLD','HOLD','H'],['SECOND','2ND','2ND']];
const blankCmds=()=>({POWER:'',ZERO:'',TARE:'',HOLD:'',SECOND:''});
const makeProfile=(name='ÖZEL KANTAR')=>({
  id:'p'+Date.now()+Math.random().toString(16).slice(2,7),name,
  wifi:{encoding:'ASCII',suffix:'CRLF',cmds:blankCmds()},
  bt:{encoding:'ASCII',suffix:'CRLF',cmds:blankCmds()},
  ir:{frequency:0,cmds:blankCmds()},repeat:1,gap:120
});
const generic=makeProfile('GENEL ASCII · ÖRNEK');generic.id='generic';generic.wifi.cmds={POWER:'P',ZERO:'Z',TARE:'T',HOLD:'H',SECOND:'F2'};generic.bt.cmds={...generic.wifi.cmds};
const custom=makeProfile('ÖZEL / MANUEL');custom.id='custom';
const DEF={enabled:true,showUser:true,powerConfirm:true,defaultTransport:'AUTO',activeProfile:'custom',profiles:[custom,generic]};
let cfg=load(),lastTransport=cfg.defaultTransport||'AUTO';
function toast(t){try{window.MUBEL&&MUBEL.toast(t)}catch(e){}}
function clone(x){return JSON.parse(JSON.stringify(x))}
function load(){try{const x=JSON.parse(localStorage.getItem(STORE)||'null');if(x&&Array.isArray(x.profiles)&&x.profiles.length){return normalize(x)}}catch(e){}return clone(DEF)}
function normalize(x){x.enabled=x.enabled!==false;x.showUser=x.showUser!==false;x.powerConfirm=x.powerConfirm!==false;x.defaultTransport=['AUTO','WIFI','BLUETOOTH','IR'].includes(x.defaultTransport)?x.defaultTransport:'AUTO';x.profiles=(x.profiles||[]).map(p=>{const n=makeProfile(p.name||'KANTAR');n.id=p.id||n.id;n.name=p.name||n.name;['wifi','bt'].forEach(k=>{if(p[k]){n[k].encoding=['ASCII','HEX','BASE64'].includes(p[k].encoding)?p[k].encoding:'ASCII';n[k].suffix=['NONE','CR','LF','CRLF'].includes(p[k].suffix)?p[k].suffix:'CRLF';n[k].cmds=Object.assign(blankCmds(),p[k].cmds||{})}});if(p.ir){n.ir.frequency=Math.max(0,parseInt(p.ir.frequency)||0);n.ir.cmds=Object.assign(blankCmds(),p.ir.cmds||{})}n.repeat=Math.min(5,Math.max(1,parseInt(p.repeat)||1));n.gap=Math.min(2000,Math.max(20,parseInt(p.gap)||120));return n});if(!x.profiles.length)x.profiles=[custom];if(!x.profiles.some(p=>p.id===x.activeProfile))x.activeProfile=x.profiles[0].id;return x}
function save(){localStorage.setItem(STORE,JSON.stringify(cfg))}
function active(){return cfg.profiles.find(p=>p.id===cfg.activeProfile)||cfg.profiles[0]}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function css(){if($('v2109css'))return;const s=document.createElement('style');s.id='v2109css';s.textContent=`
.ctrlCard{background:linear-gradient(180deg,rgba(25,29,34,.98),rgba(19,22,26,.98));border:1px solid rgba(176,141,87,.38);border-radius:16px;padding:13px 14px;margin:12px 0}.ctrlHead{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}.ctrlTitle{font-weight:900;letter-spacing:.2px}.ctrlMeta{font-size:11px;color:#aeb3bb}.ctrlMode{width:auto;min-width:125px;padding:9px 10px}.ctrlGrid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px;margin-top:10px}.ctrlKey{min-height:54px;padding:8px 6px;border-radius:12px;font-size:12px;line-height:1.1}.ctrlKey strong{display:block;font-size:16px;margin-bottom:3px}.ctrlKey.power{background:#4a2828}.ctrlKey.zero{background:#243a2a}.ctrlKey.tare{background:#27384a}.ctrlKey.hold{background:#403829}.ctrlKey.second{background:#342d45}.ctrlStatus{margin-top:9px;font-size:11px;line-height:1.4;color:#aeb3bb;min-height:15px}.ucCard{border:1px solid rgba(176,141,87,.45)!important}.ucTop{display:flex;align-items:center;justify-content:space-between;gap:8px;flex-wrap:wrap}.ucBadge{font-size:11px;border:1px solid #B08D57;color:#F6F2E9;border-radius:999px;padding:5px 9px;background:#112B4A}.ucGrid2{display:grid;grid-template-columns:1fr 1fr;gap:10px}.ucGrid3{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.ucTableWrap{overflow:auto;margin-top:10px}.ucTable{width:100%;min-width:720px;border-collapse:collapse}.ucTable th,.ucTable td{padding:7px 5px;border-bottom:1px solid #363a40;vertical-align:middle}.ucTable input{padding:9px;font-family:monospace}.ucMini{font-size:11px;color:#aeb3bb;line-height:1.45}.ucTools{display:flex;gap:8px;flex-wrap:wrap;margin:9px 0}.ucTools .btn{min-height:42px;padding:9px 12px}.ucJson{min-height:105px;font:11px monospace}.ucSep{height:1px;background:#34383e;margin:13px 0}
@media(max-width:700px){.ctrlGrid{grid-template-columns:repeat(3,1fr)}.ctrlGrid .ctrlKey:nth-child(4),.ctrlGrid .ctrlKey:nth-child(5){grid-column:auto}.ucGrid2,.ucGrid3{grid-template-columns:1fr}.ctrlMode{width:100%}}
@media(max-width:390px){.ctrlGrid{grid-template-columns:repeat(2,1fr)}.ctrlGrid .ctrlKey:last-child{grid-column:1/-1}}
`;document.head.appendChild(s)}
function injectUser(){const home=$('tab-home');if(!home||$('mubelCtrlCard'))return;const weight=home.querySelector('.weight');if(!weight)return;const c=document.createElement('div');c.id='mubelCtrlCard';c.className='ctrlCard';c.innerHTML=`<div class="ctrlHead"><div><div class="ctrlTitle">KANTAR KONTROL</div><div id="ctrlProfile" class="ctrlMeta"></div></div><select id="ctrlTransport" class="ctrlMode"><option value="AUTO">OTOMATİK</option><option value="WIFI">WI‑FI</option><option value="BLUETOOTH">BLUETOOTH</option><option value="IR">KIZILÖTESİ / IR</option></select></div><div class="ctrlGrid">${COMMANDS.map(([k,l,i])=>`<button class="btn ctrlKey ${k==='POWER'?'power':k==='ZERO'?'zero':k==='TARE'?'tare':k==='HOLD'?'hold':'second'}" data-ctrl="${k}"><strong>${i}</strong>${l}</button>`).join('')}</div><div id="ctrlStatus" class="ctrlStatus">Hazır.</div>`;weight.insertAdjacentElement('afterend',c);$('ctrlTransport').value=lastTransport; $('ctrlTransport').onchange=()=>{lastTransport=$('ctrlTransport').value;setUserMeta()};c.querySelectorAll('[data-ctrl]').forEach(b=>b.onclick=()=>send(b.dataset.ctrl));setUserMeta()}
function injectAdmin(){const tab=$('tab-settings');if(!tab||$('mubelUniversalControl'))return;const anchor=$('mubelTripleCard')||tab.lastElementChild;const c=document.createElement('div');c.id='mubelUniversalControl';c.className='card ucCard';c.innerHTML=`
<div class="ucTop"><h3 style="margin:0">Universal Kantar Kumanda Motoru</h3><span class="ucBadge">2.10.9 · WI‑FI + BT + IR</span></div>
<p class="ucMini">ON/OFF, ZERO, TARE, HOLD ve 2ND komutlarını cihaz modeline göre <b>veri olarak</b> tanımlayın. Wi‑Fi ve Bluetooth için ASCII / HEX / BASE64, kızılötesi için ham darbe dizisi desteklenir. Böylece yeni kantar için uygulama kodu değiştirmek yerine yeni profil kaydedebilirsiniz.</p>
<div class="ucGrid3"><div class="field"><label>Sistem</label><select id="ucEnabled"><option value="1">Açık</option><option value="0">Kapalı</option></select></div><div class="field"><label>Kullanıcıda göster</label><select id="ucShow"><option value="1">Göster</option><option value="0">Gizle</option></select></div><div class="field"><label>Varsayılan taşıma</label><select id="ucDefault"><option value="AUTO">Otomatik</option><option value="WIFI">Wi‑Fi</option><option value="BLUETOOTH">Bluetooth</option><option value="IR">Kızılötesi / IR</option></select></div></div>
<div class="ucGrid2"><div class="field"><label>Aktif kantar profili</label><select id="ucProfile"></select></div><div class="field"><label>Profil adı</label><input id="ucName"></div></div>
<div class="ucTools"><button id="ucNew" class="btn">YENİ PROFİL</button><button id="ucClone" class="btn">KOPYALA</button><button id="ucDelete" class="btn red">SİL</button></div>
<div class="ucSep"></div>
<div class="ucGrid3"><div class="field"><label>Wi‑Fi kodlama</label><select id="ucWifiEnc"><option>ASCII</option><option>HEX</option><option>BASE64</option></select></div><div class="field"><label>Wi‑Fi satır sonu</label><select id="ucWifiSuffix"><option value="NONE">Yok</option><option value="CR">CR</option><option value="LF">LF</option><option value="CRLF">CR+LF</option></select></div><div class="field"><label>Tekrar / aralık</label><div style="display:grid;grid-template-columns:90px 1fr;gap:8px"><input id="ucRepeat" type="number" min="1" max="5"><input id="ucGap" type="number" min="20" max="2000" placeholder="ms"></div></div></div>
<div class="ucGrid3"><div class="field"><label>Bluetooth kodlama</label><select id="ucBtEnc"><option>ASCII</option><option>HEX</option><option>BASE64</option></select></div><div class="field"><label>Bluetooth satır sonu</label><select id="ucBtSuffix"><option value="NONE">Yok</option><option value="CR">CR</option><option value="LF">LF</option><option value="CRLF">CR+LF</option></select></div><div class="field"><label>IR taşıyıcı frekansı (Hz)</label><input id="ucIrFreq" type="number" min="0" max="100000" placeholder="0 = telefon destek aralığından otomatik"></div></div>
<div class="ucTableWrap"><table class="ucTable"><thead><tr><th>Komut</th><th>Wi‑Fi veri</th><th>Bluetooth veri</th><th>IR darbe dizisi (µs)</th></tr></thead><tbody>${COMMANDS.map(([k,l])=>`<tr><td><b>${l}</b></td><td><input data-wifi="${k}" placeholder="ASCII / HEX / BASE64"></td><td><input data-bt="${k}" placeholder="ASCII / HEX / BASE64"></td><td><input data-ir="${k}" placeholder="9000,4500,560,560,..."></td></tr>`).join('')}</tbody></table></div>
<div class="ucGrid2" style="margin-top:10px"><div class="field"><label>ON/OFF için onay</label><select id="ucConfirm"><option value="1">Sor</option><option value="0">Sorma</option></select></div><div class="field"><label>IR frekans notu</label><div id="ucIrInfo" class="ucMini" style="padding-top:11px">0 seçilirse telefonun desteklediği aralığa göre otomatik taşıyıcı seçilir.</div></div></div>
<div class="row"><button id="ucSave" class="btn orange">KUMANDA AYARLARINI KAYDET</button><button id="ucIrCheck" class="btn">IR DONANIMINI KONTROL ET</button></div>
<div class="ucSep"></div><details><summary><b>Profil yedekle / başka kantara aktar</b></summary><p class="ucMini">JSON dışa aktar / içe aktar ile kantar profillerini başka telefona taşıyabilirsiniz.</p><textarea id="ucJson" class="ucJson"></textarea><div class="ucTools"><button id="ucExport" class="btn">JSON DIŞA AKTAR</button><button id="ucImport" class="btn orange">JSON İÇE AKTAR</button></div></details>`;
anchor.insertAdjacentElement('afterend',c);
$('ucProfile').onchange=()=>{readAdmin();cfg.activeProfile=$('ucProfile').value;renderAdmin()};$('ucSave').onclick=saveAdmin;$('ucNew').onclick=newProfile;$('ucClone').onclick=cloneProfile;$('ucDelete').onclick=deleteProfile;$('ucExport').onclick=()=>{$('ucJson').value=JSON.stringify(cfg,null,2);toast('Profil JSON hazır')};$('ucImport').onclick=importJson;$('ucIrCheck').onclick=checkIr;renderAdmin()}
function renderProfileList(){const s=$('ucProfile');if(!s)return;s.innerHTML=cfg.profiles.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');s.value=cfg.activeProfile}
function renderAdmin(){if(!$('ucProfile'))return;renderProfileList();const p=active();$('ucEnabled').value=cfg.enabled?'1':'0';$('ucShow').value=cfg.showUser?'1':'0';$('ucConfirm').value=cfg.powerConfirm?'1':'0';$('ucDefault').value=cfg.defaultTransport;$('ucName').value=p.name;$('ucWifiEnc').value=p.wifi.encoding;$('ucWifiSuffix').value=p.wifi.suffix;$('ucBtEnc').value=p.bt.encoding;$('ucBtSuffix').value=p.bt.suffix;$('ucIrFreq').value=p.ir.frequency||0;$('ucRepeat').value=p.repeat;$('ucGap').value=p.gap;COMMANDS.forEach(([k])=>{const w=document.querySelector(`[data-wifi="${k}"]`),b=document.querySelector(`[data-bt="${k}"]`),i=document.querySelector(`[data-ir="${k}"]`);if(w)w.value=p.wifi.cmds[k]||'';if(b)b.value=p.bt.cmds[k]||'';if(i)i.value=p.ir.cmds[k]||''});updateVisibility();setUserMeta()}
function readAdmin(){if(!$('ucProfile'))return;const p=active();if(!p)return;p.name=$('ucName').value.trim()||'KANTAR';p.wifi.encoding=$('ucWifiEnc').value;p.wifi.suffix=$('ucWifiSuffix').value;p.bt.encoding=$('ucBtEnc').value;p.bt.suffix=$('ucBtSuffix').value;p.ir.frequency=Math.max(0,parseInt($('ucIrFreq').value)||0);p.repeat=Math.min(5,Math.max(1,parseInt($('ucRepeat').value)||1));p.gap=Math.min(2000,Math.max(20,parseInt($('ucGap').value)||120));COMMANDS.forEach(([k])=>{p.wifi.cmds[k]=(document.querySelector(`[data-wifi="${k}"]`)||{}).value?.trim()||'';p.bt.cmds[k]=(document.querySelector(`[data-bt="${k}"]`)||{}).value?.trim()||'';p.ir.cmds[k]=(document.querySelector(`[data-ir="${k}"]`)||{}).value?.trim()||''});cfg.enabled=$('ucEnabled').value==='1';cfg.showUser=$('ucShow').value==='1';cfg.powerConfirm=$('ucConfirm').value==='1';cfg.defaultTransport=$('ucDefault').value;lastTransport=cfg.defaultTransport}
function saveAdmin(){readAdmin();cfg=normalize(cfg);save();renderAdmin();toast('Universal kumanda ayarları kaydedildi')}
function newProfile(){readAdmin();const n=prompt('Yeni kantar profil adı','YENİ KANTAR');if(!n)return;const p=makeProfile(n.trim()||'YENİ KANTAR');cfg.profiles.push(p);cfg.activeProfile=p.id;save();renderAdmin()}
function cloneProfile(){readAdmin();const src=active();const n=prompt('Kopya profil adı',(src.name||'KANTAR')+' KOPYA');if(!n)return;const p=clone(src);p.id='p'+Date.now()+Math.random().toString(16).slice(2,7);p.name=n.trim()||'KOPYA';cfg.profiles.push(p);cfg.activeProfile=p.id;save();renderAdmin()}
function deleteProfile(){if(cfg.profiles.length<=1)return toast('En az bir profil kalmalı');const p=active();if(!confirm(`“${p.name}” profili silinsin mi?`))return;cfg.profiles=cfg.profiles.filter(x=>x.id!==p.id);cfg.activeProfile=cfg.profiles[0].id;save();renderAdmin()}
function importJson(){try{const x=normalize(JSON.parse($('ucJson').value));cfg=x;save();renderAdmin();toast('Profil JSON içe aktarıldı')}catch(e){toast('JSON geçersiz: '+e.message)}}
function updateVisibility(){const c=$('mubelCtrlCard');if(c)c.classList.toggle('hidden',!(cfg.enabled&&cfg.showUser));if($('ctrlTransport'))$('ctrlTransport').value=lastTransport}
function setUserMeta(){const p=active(),m=$('ctrlProfile');if(m)m.textContent=(p?p.name:'-')+' · '+(lastTransport==='AUTO'?'OTOMATİK':lastTransport);updateVisibility()}
function checkIr(){try{if(!window.MubelControl||typeof MubelControl.getTransportInfo!=='function')return toast('Universal kontrol servisi yok');const o=JSON.parse(MubelControl.getTransportInfo()||'{}'),ranges=(o.irRanges||[]).map(x=>`${x.min}-${x.max} Hz`).join(', ');$('ucIrInfo').textContent=o.irEmitter?`IR hazır · ${ranges||'frekans aralığı bildirilmedi'}`:'Bu telefonda Android erişimli IR vericisi yok.';toast(o.irEmitter?'IR verici hazır':'IR verici bulunamadı')}catch(e){toast('IR kontrol hatası: '+e)}}
function send(key){if(!cfg.enabled)return toast('Kantar kontrol sistemi kapalı');const p=active();if(!p)return toast('Aktif kantar profili yok');if(key==='POWER'&&cfg.powerConfirm&&!confirm('Kantara ON/OFF komutu gönderilsin mi?'))return;const mode=$('ctrlTransport')?$('ctrlTransport').value:lastTransport;lastTransport=mode;try{if(!window.MubelControl||typeof MubelControl.sendCommand!=='function')return toast('Universal kontrol servisi bulunamadı');MubelControl.sendCommand(key,mode,p.wifi.encoding,p.wifi.cmds[key]||'',p.wifi.suffix,p.bt.encoding,p.bt.cmds[key]||'',p.bt.suffix,parseInt(p.ir.frequency)||0,p.ir.cmds[key]||'',p.repeat||1,p.gap||120);setCtrlStatus(`${COMMANDS.find(x=>x[0]===key)?.[1]||key} · ${mode} · gönderiliyor…`)}catch(e){toast('Komut gönderilemedi: '+e)}}
function setCtrlStatus(t,ok){const e=$('ctrlStatus');if(e){e.textContent=t;e.style.color=ok===true?'#7dd33b':ok===false?'#ff6464':'#aeb3bb'}}
window.MUBEL_CTRL_STATUS=(state,detail,transport,command)=>{const ok=state==='OK';setCtrlStatus(`${command||''} · ${transport||''} · ${detail||state}`,ok);if(!ok&&state==='HATA')toast(detail||'Komut gönderilemedi')};
window.MUBEL_CTRL_REFRESH=()=>{cfg=load();lastTransport=cfg.defaultTransport||'AUTO';renderAdmin();setUserMeta()};
window.MUBEL_CTRL_CI=()=>{try{if(!window.MubelControl)return;const seq=['POWER','ZERO','TARE','HOLD','SECOND'];seq.forEach((k,i)=>setTimeout(()=>MubelControl.sendCommand(k,'WIFI','ASCII','CI_'+k,'LF','ASCII','','NONE',0,'',1,80),i*280))}catch(e){}};
function boot(){css();document.querySelectorAll('.ver').forEach((e,i)=>{e.textContent=i===0?'v2.10.9':'v2.10.9 · Android'});injectUser();injectAdmin();setUserMeta();const badge=$('mubelTripleCard')?.querySelector('.tripleBadge');if(badge)badge.textContent='2.10.8 STABİL + UNIVERSAL KUMANDA 2.10.9'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();setTimeout(boot,700);setTimeout(boot,1600);
})();
