(()=>{'use strict';
const COMMANDS=[['POWER','ON / OFF'],['ZERO','ZERO'],['TARE','TARE'],['PRINT','PRINT'],['VERIFY','VERIFY'],['SWITCH','SWITCH'],['HOLD','HOLD'],['SECOND','2ND']];
const STORE='mubel2111_learn_v1';
const defaults={active:'densi-cx10t',profiles:[{id:'densi-cx10t',brand:'DENSI',model:'CX-10T (OCS-10t)',frequency:38000,learned:{}},{id:'necklife-ocsa',brand:'NECKLIFE',model:'OCS-A',frequency:38000,learned:{}}]};
let db=load();
function load(){try{let x=JSON.parse(localStorage.getItem(STORE)||'null');if(x&&Array.isArray(x.profiles))return x}catch(e){}return JSON.parse(JSON.stringify(defaults))}
function save(){localStorage.setItem(STORE,JSON.stringify(db))}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function profile(){return db.profiles.find(x=>x.id===db.active)||db.profiles[0]}
function toast(t){try{window.MUBEL&&MUBEL.toast(t)}catch(e){}}
function css(){if(document.getElementById('v2111css'))return;let s=document.createElement('style');s.id='v2111css';s.textContent='.learnCard{border:1px solid rgba(176,141,87,.55)!important}.learnBadge{display:inline-block;padding:5px 9px;border-radius:999px;background:#112B4A;color:#F6F2E9;border:1px solid #B08D57;font-size:11px}.learnGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.learnRow{padding:9px;border:1px solid #353a40;border-radius:12px}.learnRow.ok{border-color:#35a854}.learnRow .state{font-size:11px;margin:5px 0;color:#aaa}.learnRow.ok .state{color:#55d276}.learnBtns{display:flex;gap:6px}.learnBtns button{flex:1;min-height:38px}.learnRaw{width:100%;min-height:58px;font:11px monospace}.learnNote{font-size:11px;line-height:1.45;color:#aeb3bb}@media(max-width:520px){.learnGrid{grid-template-columns:1fr}}';document.head.appendChild(s)}
function inject(){let tab=document.getElementById('tab-settings');if(!tab||document.getElementById('mubel2111Learn'))return;css();let anchor=document.getElementById('mubelUniversalControl')||tab.lastElementChild;let c=document.createElement('div');c.id='mubel2111Learn';c.className='card learnCard';c.innerHTML=`<div style="display:flex;justify-content:space-between;gap:8px;align-items:center;flex-wrap:wrap"><h3 style="margin:0">KUMANDAYI ÖĞRET</h3><span class="learnBadge">2.10.11 STABİL</span></div><p class="learnNote"><b>2.10.10/2.10.9 işlevleri korunur.</b> Burada gerçek kumanda kodunu profile kaydedebilirsiniz. Telefonun standart IR vericisi bilinmeyen kumandayı dinleyemez; bilinmeyen IR kodu için harici IR öğrenici çıktısını RAW olarak girin. Yeşil ✓ yalnız kaydedilmiş gerçek kodu gösterir.</p><div class="field"><label>Kantar profili</label><select id="lProfile"></select></div><div id="lMeta" class="learnNote"></div><div class="learnGrid" id="lGrid"></div><div class="field" style="margin-top:10px"><label>Öğrenici RAW çıktısı (µs)</label><textarea id="lRaw" class="learnRaw" placeholder="Örn. harici öğrenicinin verdiği gerçek darbe dizisini buraya yapıştırın"></textarea></div><div class="row"><button id="lExport" class="btn">PROFİL JSON</button><button id="lClear" class="btn red">SEÇİLİ PROFİLİ TEMİZLE</button></div><textarea id="lJson" class="learnRaw" style="display:none"></textarea>`;anchor.insertAdjacentElement('afterend',c);document.getElementById('lProfile').onchange=e=>{db.active=e.target.value;save();render()};document.getElementById('lExport').onclick=()=>{let j=document.getElementById('lJson');j.style.display='block';j.value=JSON.stringify(profile(),null,2)};document.getElementById('lClear').onclick=()=>{if(confirm('Bu profilde öğrenilen kumanda kodları temizlensin mi?')){profile().learned={};save();render()}};render()}
function render(){let p=profile(),sel=document.getElementById('lProfile');if(!sel)return;sel.innerHTML=db.profiles.map(x=>`<option value="${esc(x.id)}">${esc(x.brand)} · ${esc(x.model)}</option>`).join('');sel.value=p.id;document.getElementById('lMeta').innerHTML=`<b>${esc(p.brand)} ${esc(p.model)}</b> · IR başlangıç ${p.frequency||38000} Hz`;let g=document.getElementById('lGrid');g.innerHTML=COMMANDS.map(([k,l])=>{let v=p.learned[k];return `<div class="learnRow ${v?'ok':''}"><b>${l}</b><div class="state">${v?'✓ ÖĞRENİLDİ · '+esc(v.frequency)+' Hz':'● HENÜZ ÖĞRETİLMEDİ'}</div><div class="learnBtns"><button class="btn orange" data-learn="${k}">ÖĞRET</button><button class="btn" data-test="${k}" ${v?'':'disabled'}>TEST ET</button></div></div>`}).join('');g.querySelectorAll('[data-learn]').forEach(b=>b.onclick=()=>learn(b.dataset.learn));g.querySelectorAll('[data-test]').forEach(b=>b.onclick=()=>test(b.dataset.test))}
function validRaw(s){let a=s.trim().split(/[,;\s]+/).filter(Boolean);return a.length>=2&&a.length<=1024&&a.every(x=>/^\d+$/.test(x)&&+x>0&&+x<=1000000)}
function learn(k){let raw=document.getElementById('lRaw').value.trim();if(!validRaw(raw)){toast('Gerçek IR öğrenici RAW çıktısını girin');return}let f=prompt('IR frekansı (Hz)',String(profile().frequency||38000));f=parseInt(f)||38000;profile().frequency=f;profile().learned[k]={transport:'IR',frequency:f,raw,verified:false,learnedAt:new Date().toISOString()};save();render();toast(k+' kodu profile kaydedildi; TEST ET ile doğrulayın')}
function test(k){let v=profile().learned[k];if(!v)return;try{if(!window.MubelControl){toast('Kumanda köprüsü hazır değil');return}MubelControl.sendCommand(k,'IR','','','NONE','','','NONE',v.frequency,v.raw,1,120);setTimeout(()=>{if(confirm(k+' komutu kantarda doğru çalıştı mı?')){v.verified=true;save();render();toast('✓ '+k+' doğrulandı')}} ,450)}catch(e){toast('Test gönderilemedi: '+e.message)}}
function boot(){inject();setInterval(inject,1500)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
